#!/usr/bin/env python3
import json, sys
import t
from t import as_, as_commit, expect, last, UID, L1, L2, L3, L4, run

t.reset()
out, err, rc = t.apply('20260919a_OPS_fence_1_safe_now.sql')
expect('file A applies', rc == 0, err[-1500:])

# an order written by an OLD customer page (direct insert) in the last day
run(f"insert into public.order_queue (ref, location_id, type, source, status, items, total) values ('OLD-1', '{L1}', 'collection', 'online', 'prep', '[]', 5);")
out, err, rc = t.apply('20260919b_OPS_fence_2_after_app.sql')
expect('file B stops while devices run the old app', rc != 0 and 'not ready' in err, err[-600:])
run("update public.devices set client_caps = array['fence_v1','device_secret'] where status in ('active','online') and bound_via is not null")
out, err, rc = t.apply('20260919b_OPS_fence_2_after_app.sql')
expect('file B stops while old customer pages still write orders', rc != 0 and 'old customer pages' in err, err[-600:])
run("update public.order_queue set created_at = now() - interval '2 days' where ref = 'OLD-1'")
out, err, rc = t.apply('20260919b_OPS_fence_2_after_app.sql')
expect('file B applies once the app is live everywhere', rc == 0, err[-2000:])
print('   verify row:', last(out))
v = last(out).split('|')
expect('no open policy left, names on, devices not readable by all, no saved codes, QR trigger on',
       v == ['none', 't', 'f', '0', 't'], last(out))
out, err, rc = t.apply('20260919b_OPS_fence_2_after_app.sql')
expect('file B applies a second time', rc == 0, err[-1500:])

# devices
o, e, r = as_('attacker', "select count(*) from public.devices;")
expect('a stranger reads no device row', last(o) == '0', o + e)
o, e, r = as_('dev1', "select count(*) from public.devices;")
n_l1, _, _ = run(f"select count(*) from public.devices where location_id = '{L1}'")
expect('a till reads its own venue devices', last(o) == n_l1, o + e + ' vs ' + n_l1)
o, e, r = as_('owner1', "select count(*) from public.devices;")
expect('Back Office reads its venue devices', last(o) == n_l1, o + e)
o, e, r = as_('dev1b', "select coalesce(public.claim_device('APPLE-1111')::text, 'null');")
expect('no re-link by saved code after file 2', last(o) == 'null', o + e)
o, e, r = as_commit('owner1', f"insert into public.devices (location_id, name, type, pairing_code, status) values ('{L1}', 'B till', 'pos', 'APPLE-9999', 'unpaired');")
o2, _, _ = run("select pairing_code from public.devices where name = 'B till'")
expect('a browser made code is replaced by a server code', o2 != 'APPLE-9999' and len(o2) == 14, o2)
o, e, r = as_commit('owner1', "select public.issue_pairing_code(id)->>'code' from public.devices where name = 'B till';")
code = last(o)
o, e, r = as_('newtill', f"select public.claim_device_v2('{code}')->>'ok';")
expect('new till pairs with the issued code', last(o) == 'true', o + e)

# orders
o, e, r = as_('attacker', "select count(*) from public.order_queue;")
expect('a stranger reads no orders', last(o) == '0', o + e)
o, e, r = as_('attacker', f"insert into public.order_queue (ref, location_id, type, source, status, items) values ('X1', '{L1}', 'collection', 'online', 'prep', '[]');")
expect('a stranger cannot insert an order', r != 0, e)
o, e, r = as_('attacker', "with u as (update public.order_queue set status = 'collected' returning 1) select count(*) from u;")
expect('a stranger updates no order', last(o) == '0', o + e)
o, e, r = as_('dev1', f"insert into public.order_queue (ref, location_id, type, source, status, items) values ('POS-1', '{L1}', 'collection', 'pos', 'prep', '[]'); select count(*) from public.order_queue;")
expect('a till writes and reads its venue orders', r == 0 and int(last(o)) >= 1, o + e)
o, e, r = as_('dev1', f"insert into public.order_queue (ref, location_id, type, source, status, items) values ('POS-2', '{L3}', 'collection', 'pos', 'prep', '[]');")
expect('a till cannot write another venue orders', r != 0, e)
o, e, r = as_('dev4', f"insert into public.order_queue (ref, location_id, type, source, status, items) values ('K-1', '{L1}', 'collection', 'kiosk', 'prep', '[]');")
expect('a kiosk writes its venue orders', r == 0, e)
o, e, r = as_('owner1', "select count(*) from public.order_queue;")
expect('Back Office reads its orders', r == 0 and int(last(o)) >= 1, o + e)
o, e, r = as_('rawanon', f"insert into public.order_queue (ref, location_id, type, source, status, items) values ('X2', '{L1}', 'collection', 'online', 'prep', '[]');")
expect('raw anon key cannot insert orders', r != 0 and 'permission denied' in e, e)
# kds and print
o, e, r = as_('dev1', f"insert into public.kds_tickets (id, location_id, items) values ('k1', '{L1}', '[]');")
expect('a till writes KDS tickets', r == 0, e)
o, e, r = as_('attacker', f"insert into public.kds_tickets (id, location_id, items) values ('k2', '{L1}', '[]');")
expect('a stranger cannot write KDS tickets', r != 0, e)
o, e, r = as_('attacker', "select count(*) from public.kds_tickets;")
expect('a stranger reads no KDS tickets', last(o) == '0', o + e)
o, e, r = as_('dev1', f"insert into public.print_jobs (location_id, printer_id, printer_ip, job_type, payload, status) values ('{L1}', 'p', '1.2.3.4', 'receipt', 'eA==', 'pending');")
expect('a till writes print jobs', r == 0, e)
o, e, r = as_('rawanon', "select count(*) from public.print_jobs;")
expect('raw anon key reads no print jobs', last(o) == '0', o + e)
run(f"insert into public.print_jobs (location_id, printer_id, printer_ip, job_type, payload, status) values ('{L1}', 'p1', '10.0.0.5', 'receipt', 'eA==', 'pending');")
o, e, r = as_commit('owner1', f"select public.issue_print_agent_token('{L1}', 'agent')->>'token';")
agent = last(o)
o, e, r = as_('rawanon', f"select jsonb_array_length(public.print_agent_claim('{agent}', 'a1')->'jobs');")
expect('print agent still claims jobs with its key', last(o) == '1', o + e)
# tables
o, e, r = as_('dev1', f"insert into public.active_sessions (location_id, table_id, session) values ('{L1}', 't1', '{{}}');")
expect('a till writes table sessions', r == 0, e)
o, e, r = as_('attacker', "select count(*) from public.active_sessions;")
expect('a stranger reads no table sessions', last(o) == '0', o + e)
o, e, r = as_('attacker', f"insert into public.active_sessions (location_id, table_id, session) values ('{L1}', 't2', '{{}}');")
expect('a stranger cannot write table sessions', r != 0, e)
run(f"insert into public.waitlist_devices (device_uid, name, location_id, active) values ('{UID['customer']}', 'Host', '{L1}', true);")
o, e, r = as_('customer', f"insert into public.active_sessions (location_id, table_id, session) values ('{L1}', 't3', '{{}}');")
expect('the venue host stand still seats guests (B4)', r == 0, e)
o, e, r = as_('dev1', f"insert into public.table_reservations (location_id, table_id, reservation) values ('{L1}', 't1', '{{}}');")
expect('a till writes table reservations', r == 0, e)
o, e, r = as_('attacker', "select count(*) from public.table_reservations;")
expect('a stranger reads no reservations', last(o) == '0', o + e)
# payments
o, e, r = as_('attacker', f"insert into public.closed_checks (id, location_id, source, status, total) values ('fake', '{L1}', 'online', 'paid', 999);")
expect('a stranger cannot insert paid revenue (B3)', r != 0, e)
o, e, r = as_('dev1', f"insert into public.closed_checks (id, location_id, source, status, total) values ('real', '{L1}', 'pos', 'paid', 9);")
expect('a till closes a check', r == 0, e)
o, e, r = as_('dev4', f"insert into public.closed_checks (id, location_id, source, status, total, kiosk_id) values ('kio', '{L1}', 'kiosk', 'paid', 9, '40000000-0000-4000-8000-000000000004');")
expect('a kiosk closes a check', r == 0, e)
# customer path end to end, with the QR floor trigger
run(f"insert into public.floor_tables (id, location_id, label) values ('ft-7', '{L1}', 'T7') on conflict do nothing;")
run(f"insert into public.payment_proofs (processor, payment_ref, kind, location_id, amount_minor, verified_by) values ('stripe', 'pi_tab_000000009', 'preauth', '{L1}', 5000, 'test');")
tab = json.dumps({'ref': 'QR-B1', 'source': 'qr', 'type': 'dine-in', 'items': [{'name': 'Beer', 'price': 6, 'qty': 2}], 'total': 12,
                  'customer': {'name': 'Bob', 'tableId': 'T7', 'tab_open': True, 'payment_intent_id': 'pi_tab_000000009'}}).replace("'", "''")
o, e, r = as_commit('customer', f"select public.place_public_order('{L1}', '{tab}'::jsonb)->>'ok';")
expect('QR tab opened through the function', last(o) == 'true', o + e)
o, e, r = run(f"select session->>'source', session->>'subtotal' from public.active_sessions where location_id = '{L1}' and table_id = 'ft-7'")
expect('the tab shows on the floor plan (server trigger)', o == 'qr|12', o)
run(f"insert into public.payment_proofs (processor, payment_ref, kind, location_id, amount_minor, verified_by) values ('stripe', 'pi_tab_000000009', 'capture', '{L1}', 1200, 'test');")
o, e, r = as_commit('customer', f"select public.settle_qr_tab('{L1}', 'pi_tab_000000009')->>'closed';")
expect('customer closes the tab after capture', last(o) == '1', o + e)
o, e, r = run(f"select count(*) from public.active_sessions where location_id = '{L1}' and table_id = 'ft-7'")
expect('the closed tab leaves the floor plan', o == '0', o)
o, e, r = as_('rawanon', f"select public.order_track_row('{L1}', 'QR-B1', 'pi_tab_000000009')->>'status';")
expect('tracker by card payment id (QR)', last(o) == 'collected', o + e)

fails = [n for n, ok, d in t.RESULTS if not ok]
print(f"\n{len(t.RESULTS) - len(fails)} passed, {len(fails)} failed")
sys.exit(1 if fails else 0)
