// src/backoffice/sections/reports/AdyenStatements.jsx
// ServOS Payments — Documents tab (v5.6.99). Pick a month; when the ledger has
// fee data for it (settlement ingestion ran), render a clean statement and a
// Print button — the browser's print-to-PDF is the delivery mechanism for now.
// Data via adyen-financial action 'statement'. No fee data for the month =
// the same honest setup story as the Payouts tab.

import { useEffect, useState } from 'react';
import { supabase, isMock, getLocationId } from '../../../lib/supabase';
import { EmptyState } from './_charts';
import { money } from '../../../lib/currency';
import { SettlementSetupSteps } from './AdyenPayouts';

const thisMonth = () => new Date().toISOString().slice(0, 7);
const monthLabel = (ym) => {
  try { return new Date(`${ym}-01T00:00:00`).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }); }
  catch { return ym; }
};

export default function AdyenStatements() {
  const [month, setMonth] = useState(thisMonth());
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async (ym) => {
    setLoading(true); setError('');
    try {
      if (isMock) { setData({ mock: true }); return; }
      const locId = await getLocationId().catch(() => null);
      const { data: session } = await supabase.auth.getSession();
      const token = session?.session?.access_token;
      if (!token) throw new Error('Please sign in again.');
      const res = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/adyen-financial`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` },
        body: JSON.stringify({ action: 'statement', ops_location_id: locId, month: ym }),
      });
      const j = await res.json();
      if (!res.ok || j.error) throw new Error(j.error || `HTTP ${res.status}`);
      setData(j);
    } catch (e) { setError(e.message || 'Failed to load'); setData(null); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(month); }, [month]);

  const cur = data?.currency || 'GBP';
  const m = (minor) => (minor == null ? '—' : money((Number(minor) || 0) / 100, cur));

  // Print window: a self-contained page, so print-to-PDF captures ONLY the
  // statement, never the Back Office chrome around it.
  const printStatement = () => {
    if (!data) return;
    const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const line = (label, value, strong = false) => `
      <tr${strong ? ' class="strong"' : ''}><td>${esc(label)}</td><td class="num">${esc(value)}</td></tr>`;
    const partial = data.fee_coverage && data.fee_coverage.with_fees < data.fee_coverage.payments;
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>ServOS Payments statement, ${esc(monthLabel(month))}</title>
      <style>
        body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; color: #111; margin: 48px; }
        h1 { font-size: 20px; margin: 0 0 2px; }
        .sub { color: #555; font-size: 13px; margin-bottom: 28px; }
        table { width: 100%; max-width: 560px; border-collapse: collapse; font-size: 14px; }
        td { padding: 9px 4px; border-bottom: 1px solid #e3e3e3; }
        td.num { text-align: right; font-variant-numeric: tabular-nums; }
        tr.strong td { font-weight: 700; border-top: 2px solid #111; border-bottom: none; }
        .note { color: #666; font-size: 11.5px; margin-top: 26px; max-width: 560px; line-height: 1.5; }
      </style></head><body>
      <h1>${esc(data.venue || 'Venue')}</h1>
      <div class="sub">ServOS Payments statement · ${esc(monthLabel(month))}</div>
      <table>
        ${line('Card payments taken', String(data.payments_count ?? 0))}
        ${line('Gross card takings', m(data.gross_minor))}
        ${line('Refunds', data.refunds_minor ? `- ${m(data.refunds_minor)}` : m(0))}
        ${data.gratuity_minor ? line('Of which tips', m(data.gratuity_minor)) : ''}
        ${line('Processing fees', data.fees_minor != null ? `- ${m(data.fees_minor)}` : '—')}
        ${line('Net to your bank', m(data.net_minor), true)}
      </table>
      <div class="note">
        ${partial ? `Fees are recorded for ${data.fee_coverage.with_fees} of ${data.fee_coverage.payments} payments in this period; the fee and net figures cover those payments. The rest settle in the next few days and this statement updates itself.<br>` : ''}
        Generated by ServOS on ${esc(new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }))}.
        Figures come from your live payments ledger and settlement reports.
      </div>
      </body></html>`;
    const w = window.open('', '_blank', 'width=800,height=900');
    if (!w) { setError('The print window was blocked. Allow pop-ups for this site and try again.'); return; }
    w.document.write(html);
    w.document.close();
    w.focus();
    w.print();
  };

  const rows = data && data.has_fee_data ? [
    ['Card payments taken', String(data.payments_count ?? 0)],
    ['Gross card takings', m(data.gross_minor)],
    ['Refunds', data.refunds_minor ? `- ${m(data.refunds_minor)}` : m(0)],
    ...(data.gratuity_minor ? [['Of which tips', m(data.gratuity_minor)]] : []),
    ['Processing fees', data.fees_minor != null ? `- ${m(data.fees_minor)}` : '—'],
  ] : [];

  return (
    <div style={{ padding: '4px 0' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16, flexWrap: 'wrap' }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--t1)' }}>Monthly statement</div>
        <input
          type="month"
          value={month}
          max={thisMonth()}
          onChange={(e) => { if (e.target.value) setMonth(e.target.value); }}
          style={{ padding: '7px 10px', borderRadius: 8, border: '1px solid var(--bdr)', background: 'var(--bg1)', color: 'var(--t1)', fontSize: 13, fontFamily: 'inherit', colorScheme: 'dark light' }}
        />
        {data?.has_fee_data && (
          <button onClick={printStatement} style={{ padding: '7px 14px', borderRadius: 8, background: 'var(--acc)', border: 'none', color: '#fff', fontSize: 12.5, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit' }}>
            Print / save as PDF
          </button>
        )}
      </div>

      {loading && <div style={{ padding: 24, color: 'var(--t3)' }}>Building statement…</div>}
      {!loading && error && <EmptyState icon="⚠️" message={error} />}
      {!loading && !error && data?.mock && <EmptyState icon="📄" message="Statements are live only — view them on the deployed app." />}

      {!loading && !error && data && !data.mock && !data.has_fee_data && (
        <>
          <EmptyState icon="📄" message={`No statement for ${monthLabel(month)} yet. Statements build from settlement fee data, which appears once settlement reporting is switched on.`} />
          <SettlementSetupSteps />
        </>
      )}

      {!loading && !error && data?.has_fee_data && (
        <div style={{ background: 'var(--bg1)', border: '1px solid var(--bdr)', borderRadius: 12, padding: '22px 24px', maxWidth: 560 }}>
          <div style={{ fontSize: 16, fontWeight: 800, color: 'var(--t1)' }}>{data.venue || 'This venue'}</div>
          <div style={{ fontSize: 12.5, color: 'var(--t3)', marginBottom: 16 }}>ServOS Payments statement · {monthLabel(month)}</div>
          {rows.map(([label, value]) => (
            <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 0', borderBottom: '1px solid var(--bdr)', fontSize: 13.5 }}>
              <div style={{ color: 'var(--t2)' }}>{label}</div>
              <div style={{ color: 'var(--t1)', fontVariantNumeric: 'tabular-nums' }}>{value}</div>
            </div>
          ))}
          <div style={{ display: 'flex', justifyContent: 'space-between', padding: '11px 0 2px', fontSize: 14.5, fontWeight: 800 }}>
            <div style={{ color: 'var(--t1)' }}>Net to your bank</div>
            <div style={{ color: 'var(--grn)', fontVariantNumeric: 'tabular-nums' }}>{m(data.net_minor)}</div>
          </div>
          {data.fee_coverage && data.fee_coverage.with_fees < data.fee_coverage.payments && (
            <div style={{ fontSize: 11.5, color: 'var(--t3)', marginTop: 12, lineHeight: 1.5 }}>
              Fees are recorded for {data.fee_coverage.with_fees} of {data.fee_coverage.payments} payments so far.
              The rest settle over the next few days and this statement updates itself.
            </div>
          )}
        </div>
      )}
    </div>
  );
}
